# crawler/config/seeds.py

DEFAULT_SEED_POLICY = {
    "crawl_enabled": True,
    "priority": "P1",
    "source_group": None,
    "discover_board_candidates": False,
}


def normalize_seed(seed: dict) -> dict:
    normalized = {**DEFAULT_SEED_POLICY, **seed}
    normalized["source_group"] = normalized.get("source_group") or normalized.get("source_type")

    if "discover_board_candidates" not in seed:
        normalized["discover_board_candidates"] = normalized.get("page_kind") in {"seed", "static_page"}

    return normalized


def iter_seed_catalog(page_kind: str | None = None) -> list[dict]:
    seeds = [normalize_seed(seed) for seed in SEED_URLS]
    if page_kind is not None:
        seeds = [seed for seed in seeds if seed.get("page_kind") == page_kind]
    return seeds


def iter_enabled_seeds(page_kind: str | None = None) -> list[dict]:
    return [seed for seed in iter_seed_catalog(page_kind) if seed.get("crawl_enabled", True)]

SEED_URLS = [       # 해당 크롤러는 밑의 주소의 정보를 크롤링함
    {
        "name": "deu_home",
        "url": "https://www.deu.ac.kr/www/index.do",
        "source_type": "homepage",
        "page_kind": "static_page",
        "priority": "P0",
    },
    {
        "name": "deu_president_message",
        "url": "https://www.deu.ac.kr/www/deu-message.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P1",
    },
    {
        "name": "deu_student_council",
        "url": "https://www.deu.ac.kr/www/deu-student-council.do",
        "source_type": "student_life",
        "page_kind": "static_page",
        "priority": "P1",
    },
    {
        "name": "deu_former_presidents",
        "url": "https://www.deu.ac.kr/www/former-university-presidents.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_campus_map",
        "url": "https://www.deu.ac.kr/www/deu-campus-map.do",
        "source_type": "campus",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_campus_gaya",
        "url": "https://www.deu.ac.kr/www/deu-campus-gaya.do",
        "source_type": "campus",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_university_philosophy",
        "url": "https://www.deu.ac.kr/www/university-philosophy.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_vision",
        "url": "https://www.deu.ac.kr/www/deu-vision.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_corporation",
        "url": "https://www.deu.ac.kr/www/deu-corporation.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_foundation_notices_list",
        "url": "https://www.deu.ac.kr/www/deu-foundation-notices.do?mode=list",
        "source_type": "foundation_notice",
        "page_kind": "board_list",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_foundation_mom",
        "url": "https://www.deu.ac.kr/www/deu-foundation-mom.do",
        "source_type": "foundation",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_safety",
        "url": "https://www.deu.ac.kr/www/deu-safety.do",
        "source_type": "safety",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_overview",
        "url": "https://www.deu.ac.kr/www/deu-overview.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_history_2020",
        "url": "https://www.deu.ac.kr/www/deu-history-2020.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P3",
        "crawl_enabled": True,
    },
    {
        "name": "deu_council_notice_list",
        "url": "https://www.deu.ac.kr/www/deu-council-notice.do?mode=list",
        "source_type": "council_notice",
        "page_kind": "board_list",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ui",
        "url": "https://www.deu.ac.kr/www/deu-ui.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P3",
        "crawl_enabled": True,
    },
    {
        "name": "deu_song",
        "url": "https://www.deu.ac.kr/www/deu-song.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P3",
        "crawl_enabled": True,
    },
    {
        "name": "deu_character",
        "url": "https://www.deu.ac.kr/www/deu-character.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P3",
        "crawl_enabled": True,
    },
    {
        "name": "deu_affiliated_institution",
        "url": "https://www.deu.ac.kr/www/deu-affiliated-Institution.do",
        "source_type": "institution",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_college",
        "url": "https://www.deu.ac.kr/www/deu-college.do",
        "source_type": "academic",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_graduate_school",
        "url": "https://www.deu.ac.kr/www/deu-graduate-school.do",
        "source_type": "academic",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_rule",
        "url": "https://www.deu.ac.kr/www/deu-rule.do",
        "source_type": "academic",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_curriculum",
        "url": "https://www.deu.ac.kr/www/deu-curriculum.do",
        "source_type": "academic",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_explanation",
        "url": "https://www.deu.ac.kr/www/deu-explanation.do",
        "source_type": "academic",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_microdegree",
        "url": "https://www.deu.ac.kr/www/deu-microdegree.do",
        "source_type": "academic",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_consortium",
        "url": "https://www.deu.ac.kr/www/deu-consortium.do",
        "source_type": "academic",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_rnd",
        "url": "https://www.deu.ac.kr/www/deu-rnd.do",
        "source_type": "research",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_notice_list",
        "url": "https://www.deu.ac.kr/www/deu-notice.do?mode=list",
        "source_type": "notice",
        "page_kind": "board_list",
        "priority": "P0",
        "crawl_enabled": True,
    },
    {
        "name": "deu_scholarship_list",
        "url": "https://www.deu.ac.kr/www/deu-scholarship.do?mode=list",
        "source_type": "scholarship",
        "page_kind": "board_list",
        "priority": "P0",
    },
    {
        "name": "deu_gra_notice_list",
        "url": "https://www.deu.ac.kr/www/gra-notice.do?mode=list",
        "source_type": "academic_notice",
        "page_kind": "board_list",
        "priority": "P0",
    },
    {
        "name": "deu_education_list",
        "url": "https://www.deu.ac.kr/www/deu-education.do?mode=list",
        "source_type": "education",
        "page_kind": "board_list",
        "priority": "P1",
    },
    {
        "name": "deu_job_list",
        "url": "https://www.deu.ac.kr/www/deu-job.do?mode=list",
        "source_type": "job",
        "page_kind": "board_list",
        "priority": "P1",
    },
    {
        "name": "deu_support_notice_list",
        "url": "https://www.deu.ac.kr/www/deu-support-notice.do?mode=list",
        "source_type": "disability_support",
        "page_kind": "board_list",
        "priority": "P1",
    },
    {
        "name": "deu_bids_list",
        "url": "https://www.deu.ac.kr/www/deu-bids.do?mode=list",
        "source_type": "bids",
        "page_kind": "board_list",
        "priority": "P2",
    },
    {
        "name": "deu_today_list",
        "url": "https://www.deu.ac.kr/www/deu-today.do?mode=list",
        "source_type": "news",
        "page_kind": "board_list",
        "priority": "P2",
    },
    {
        "name": "deu_ipsi_home",
        "url": "https://ipsi.deu.ac.kr/main.do",
        "source_type": "admission",
        "page_kind": "static_page",
        "priority": "P0",
    },
    {
        "name": "deu_ipsi_susi_guide",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuord=1",
        "source_type": "admission",
        "page_kind": "static_page",
    },
    {
        "name": "deu_ipsi_jungsi_guide",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuord=2",
        "source_type": "admission",
        "page_kind": "static_page",
    },
    {
        "name": "deu_ipsi_submenu_d0lb4mk2",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuUrl=D0Lb4Mk2mKJBZuJJDzIzEw%3D%3D",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_submenu_ye0oe4wa",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuUrl=Ye0Oe4WAUjlEoUsext6iJw%3D%3D",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_menuord_3",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuord=3",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_submenu_cpat8s71",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuUrl=Cpat8s71FjlAdfevJKfIDw%3D%3D",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_transfer_archive",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuUrl=PfBqkhQSW5ucDw9DG8WhnQ%3D%3D",
        "source_type": "admission",
        "page_kind": "static_page",
    },
    {
        "name": "deu_ipsi_submenu_cf5pbokb",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuUrl=Cf5PbokbyGk5VfLO98MtrA%3D%3D",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_submenu_plus3jey",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuUrl=%2B3JEYt36zn8xvrwKcNVv3w%3D%3D",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_menuord_5",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuord=5",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_submenu_khw0im8v",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuUrl=KHw0IM8v%2BcgQ4zs30Ih%2B4w%3D%3D",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_menuord_6",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuord=6",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_submenu_dlhayfis",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuUrl=dLhAYFiSDJmIo3FeS8m3ug%3D%3D",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_university_detail",
        "url": "https://ipsi.deu.ac.kr/universityDetail.do",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_ipsi_menuord_7",
        "url": "https://ipsi.deu.ac.kr/submenu.do?menuord=7",
        "source_type": "admission",
        "source_group": "admission",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },
    {
        "name": "deu_academic_support_home",
        "url": "https://dess.deu.ac.kr/",
        "source_type": "academic_support",
        "page_kind": "static_page",
    },
    {
        "name": "deu_dorm_home",
        "url": "https://dorm.deu.ac.kr/",
        "source_type": "dormitory",
        "page_kind": "static_page",
    },
    {
        "name": "deu_dorm_hyomin_intro",
        "url": "https://dorm.deu.ac.kr/10/1010.do",
        "source_type": "dormitory",
        "page_kind": "static_page",
    },
    {
        "name": "deu_dorm_hyomin_admission",
        "url": "https://dorm.deu.ac.kr/30/3010.do",
        "source_type": "dormitory",
        "page_kind": "static_page",
    },
    {
        "name": "deu_happy_dorm_intro",
        "url": "https://dorm.deu.ac.kr/10/1020.do",
        "source_type": "dormitory",
        "page_kind": "static_page",
    },
    {
        "name": "deu_library_home",
        "url": "https://lib.deu.ac.kr/",
        "source_type": "library",
        "page_kind": "static_page",
    },
    {
        "name": "deu_ipp_home",
        "url": "https://ipp.deu.ac.kr/",
        "source_type": "ipp",
        "page_kind": "static_page",
    },
    {
        "name": "deu_pluscenter_home",
        "url": "https://deu.ac.kr/pluscenter/index.do",
        "source_type": "pluscenter",
        "page_kind": "static_page",
    },
    {
        "name": "deu_career_home",
        "url": "https://career.deu.ac.kr/career/Page/Default.aspx",
        "source_type": "career",
        "page_kind": "static_page",
    },
    {
        "name": "deu_shuttle_bus",
        "url": "https://www.deu.ac.kr/www/deu-bus.do",
        "source_type": "campus",
        "page_kind": "static_page",
    },
    {
        "name": "deu_dining_hall",
        "url": "https://www.deu.ac.kr/www/deu-dining-hall.do",
        "source_type": "welfare",
        "page_kind": "static_page",
    },
    {
        "name": "deu_cloud_email",
        "url": "https://www.deu.ac.kr/www/deu-cloud.do",
        "source_type": "it_service",
        "page_kind": "static_page",
    },
    {
        "name": "deu_heyyoung",
        "url": "https://www.deu.ac.kr/www/deu-heyyoung.do",
        "source_type": "it_service",
        "page_kind": "static_page",
    },
    {
        "name": "deu_facility_info",
        "url": "https://www.deu.ac.kr/www/deu-facility-info.do",
        "source_type": "facility",
        "page_kind": "static_page",
    },
    {
        "name": "deu_disability_support_info",
        "url": "https://www.deu.ac.kr/www/deu-support-info.do",
        "source_type": "disability_support",
        "page_kind": "static_page",
    },
    {
        "name": "deu_phone",
        "url": "https://www.deu.ac.kr/www/phone.do",
        "source_type": "institution",
        "page_kind": "static_page",
    },
    {
        "name": "deu_rules",
        "url": "https://www.deu.ac.kr/www/rules.do",
        "source_type": "institution",
        "page_kind": "static_page",
    },
    {
        "name": "deu_lifelong_home",
        "url": "https://lifelong.deu.ac.kr/",
        "source_type": "lifelong",
        "page_kind": "static_page",
    },
    {
        "name": "deu_ctl_home",
        "url": "https://ctl.deu.ac.kr/ctl/index.do",
        "source_type": "ctl",
        "page_kind": "static_page",
    },
    {
        "name": "deu_collabo_home",
        "url": "https://collabo.deu.ac.kr/collabo/index.do",
        "source_type": "collabo",
        "page_kind": "static_page",
    },
    {
        "name": "deu_has_home",
        "url": "https://has.deu.ac.kr/",
        "source_type": "has",
        "page_kind": "static_page",
    },
    {
        "name": "deu_bhcoss_home",
        "url": "https://bhcoss.deu.ac.kr/bhcoss/index.do",
        "source_type": "bhcoss",
        "page_kind": "static_page",
    },
    {
        "name": "deu_lang_intro_home",
        "url": "https://deuhome.deu.ac.kr/lang_intro/index.do",
        "source_type": "language_intro",
        "page_kind": "static_page",
    },
    {
        "name": "deu_language_home",
        "url": "https://deuhome.deu.ac.kr/language/index.do",
        "source_type": "language",
        "page_kind": "static_page",
    },
    {
        "name": "deu_counsel_home",
        "url": "https://counsel.deu.ac.kr/counsel/index.do",
        "source_type": "counsel",
        "page_kind": "static_page",
    },
    {
        "name": "deu_advising_home",
        "url": "https://advising.deu.ac.kr/advising/index.do",
        "source_type": "advising",
        "page_kind": "static_page",
    },
    {
        "name": "deu_webzine_home",
        "url": "https://webzine.deu.ac.kr/webzine",
        "source_type": "webzine",
        "page_kind": "static_page",
    },
    {
        "name": "deu_fund_home",
        "url": "https://deufund.deu.ac.kr/exchange/main.do",
        "source_type": "fund",
        "page_kind": "static_page",
    },
    {
        "name": "deu_research_ethics_home",
        "url": "https://reethics.deu.ac.kr/resch/index.do",
        "source_type": "research_ethics",
        "page_kind": "static_page",
        "priority": "P2",
        "crawl_enabled": True,
    },

]
