services:
  backend:
    build:
      args:
        PYTORCH_INDEX_URL: https://download.pytorch.org/whl/cu128
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    gpus: all

  rag:
    build:
      args:
        PYTORCH_INDEX_URL: https://download.pytorch.org/whl/cu128
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    gpus: all

  crawler:
    build:
      args:
        PYTORCH_INDEX_URL: https://download.pytorch.org/whl/cu128
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    gpus: all
